import "./globals.css";

export const metadata = {
  title: "Blog Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">

        <div className="main">
          <div className="gradient"/>
        </div>

        <div className="app">
          {children}
        </div>

      </body>
    </html>
  );
}
