import Provider from "@/components/Provider";
import "./globals.css";

export const metadata = {
  title: "Blog Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Provider>
          <div className="main">
            <div className="gradient"/>
          </div>

          <div className="app">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
